export const mockTickets = [
  {
    id: "TKT-001",
    location: "Osmeña Blvd",
    barangay: "Capitol Site",
    city: "Cebu City",
    reporter: "Juan Cruz",
    urgency: "High",
    status: "Pending",
    date: "2023-10-24",
    time: "08:42 AM",
    lat: 10.3117,
    lng: 123.8925,
    category: "Overflowing Bin",
    description: "Overflowing commercial garbage bin near the intersection causing spillover into sidewalk.",
  },
  {
    id: "TKT-002",
    location: "IT Park",
    barangay: "Apas",
    city: "Cebu City",
    reporter: "Maria Santos",
    urgency: "Low",
    status: "Resolved",
    date: "2023-10-23",
    time: "02:15 PM",
    lat: 10.3298,
    lng: 123.9061,
    category: "Litter",
    description: "Small food packaging litter scattered around park benches.",
  },
  {
    id: "TKT-003",
    location: "Colon St",
    barangay: "Parian",
    city: "Cebu City",
    reporter: "Pedro Reyes",
    urgency: "Critical",
    status: "In Progress",
    date: "2023-10-24",
    time: "11:20 AM",
    lat: 10.298,
    lng: 123.9026,
    category: "Illegal Dumping",
    description: "Large illegal dumping site blocking pedestrian sidewalk and drainage gutter.",
  },
  {
    id: "TKT-004",
    location: "AS Fortuna",
    barangay: "Banilad",
    city: "Mandaue City",
    reporter: "Ana Lim",
    urgency: "Medium",
    status: "Pending",
    date: "2023-10-25",
    time: "09:30 AM",
    lat: 10.34,
    lng: 123.9213,
    category: "Uncollected Waste",
    description: "Uncollected household trash bags sitting for 3 days attracting stray animals.",
  },
  {
    id: "TKT-005",
    location: "Mactan Shrine",
    barangay: "Mactan",
    city: "Lapu-Lapu City",
    reporter: "Carlos Gomez",
    urgency: "Medium",
    status: "Resolved",
    date: "2023-10-22",
    time: "04:10 PM",
    lat: 10.3105,
    lng: 124.0152,
    category: "Coastal Waste",
    description: "Plastic bottles and single-use plastics along the coastal walkway.",
  },
  {
    id: "TKT-006",
    location: "Talisay City Hall",
    barangay: "Lawaan",
    city: "Talisay City",
    reporter: "Elena Tan",
    urgency: "High",
    status: "In Progress",
    date: "2023-10-25",
    time: "01:45 PM",
    lat: 10.252,
    lng: 123.8399,
    category: "Drainage Clog",
    description: "Clogged drainage channel due to heavy solid waste accumulation.",
  },
  {
    id: "TKT-007",
    location: "Fuente Osmeña Circle",
    barangay: "Santa Cruz",
    city: "Cebu City",
    reporter: "Miguel Castro",
    urgency: "Low",
    status: "Pending",
    date: "2023-10-26",
    time: "07:15 AM",
    lat: 10.3121,
    lng: 123.8929,
    category: "Green Waste",
    description: "Fallen tree branches and pruning waste after maintenance.",
  },
  {
    id: "TKT-008",
    location: "Parkmall",
    barangay: "Tipolo",
    city: "Mandaue City",
    reporter: "Rosa Diaz",
    urgency: "Critical",
    status: "Pending",
    date: "2023-10-26",
    time: "10:05 AM",
    lat: 10.3228,
    lng: 123.9317,
    category: "Hazardous Waste",
    description: "Improperly disposed commercial chemical containers near service lane.",
  },
  {
    id: "TKT-009",
    location: "Opon Mercado",
    barangay: "Poblacion",
    city: "Lapu-Lapu City",
    reporter: "Luisa Perez",
    urgency: "High",
    status: "Resolved",
    date: "2023-10-21",
    time: "05:50 PM",
    lat: 10.3129,
    lng: 123.9511,
    category: "Organic Waste",
    description: "Rotten organic produce waste accumulating outside market perimeter.",
  },
  {
    id: "TKT-010",
    location: "SRP Coastal Road",
    barangay: "San Roque",
    city: "Talisay City",
    reporter: "Victor Manuel",
    urgency: "Medium",
    status: "In Progress",
    date: "2023-10-25",
    time: "03:25 PM",
    lat: 10.2647,
    lng: 123.8568,
    category: "Debris",
    description: "Construction debris and gravel spillage along emergency shoulder.",
  },
  {
    id: "TKT-011",
    location: "Carbon Market",
    barangay: "Ermita",
    city: "Cebu City",
    reporter: "Sofia Fernandez",
    urgency: "Critical",
    status: "Pending",
    date: "2023-10-26",
    time: "06:40 AM",
    lat: 10.2934,
    lng: 123.8986,
    category: "Illegal Dumping",
    description: "Massive mixed waste pile blocking vendor delivery pathway.",
  },
  {
    id: "TKT-012",
    location: "Ayala Center Cebu",
    barangay: "Luz",
    city: "Cebu City",
    reporter: "Rafael Garcia",
    urgency: "Low",
    status: "Resolved",
    date: "2023-10-20",
    time: "01:10 PM",
    lat: 10.3185,
    lng: 123.9056,
    category: "Litter",
    description: "Spilled liquid and cardboard cartons near transit terminal.",
  },
];

export const mockDashboardStats = {
  totalReports: 12,
  pending: 5,
  inProgress: 3,
  resolved: 4,
  responseTime: "4.2 hrs",
  resolutionRate: "89%",
  activeTrucks: 8,
  totalTrucks: 10,
  monthlyTonnage: "1,420 t",
};

export const mockRecentActivity = [
  {
    id: "ACT-01",
    type: "status_change",
    title: "TKT-003 escalated to In Progress",
    description: "Truck 04 (Plate GW-8821) dispatched to Colon St, Brgy. Parian.",
    timestamp: "12m ago",
    badge: "Dispatch",
  },
  {
    id: "ACT-02",
    type: "new_ticket",
    title: "New Incident Filed: TKT-011",
    description: "Critical illegal dumping reported in Carbon Market, Brgy. Ermita.",
    timestamp: "38m ago",
    badge: "Alert",
  },
  {
    id: "ACT-03",
    type: "resolved",
    title: "TKT-002 Marked Resolved",
    description: "Sanitation Team 2 completed cleanup at Cebu IT Park.",
    timestamp: "2h ago",
    badge: "Resolved",
  },
  {
    id: "ACT-04",
    type: "fleet",
    title: "Route Optimized for Sector 4",
    description: "AI dispatcher re-routed Truck 02 to alleviate Guadalupe backlog.",
    timestamp: "4h ago",
    badge: "System",
  },
];

export const mockAnalyticsData = {
  monthlyReports: [
    { month: "May", count: 85, resolved: 78 },
    { month: "Jun", count: 110, resolved: 102 },
    { month: "Jul", count: 95, resolved: 90 },
    { month: "Aug", count: 128, resolved: 119 },
    { month: "Sep", count: 135, resolved: 124 },
    { month: "Oct", count: 142, resolved: 126 },
  ],
  categories: [
    { name: "Illegal Dumping", count: 38, percentage: "27%" },
    { name: "Overflowing Bins", count: 42, percentage: "30%" },
    { name: "Uncollected Waste", count: 31, percentage: "22%" },
    { name: "Drainage Clogs", count: 19, percentage: "13%" },
    { name: "Green/Debris Waste", count: 12, percentage: "8%" },
  ],
  barangayRankings: [
    { name: "Guadalupe", reports: 28, resolvedRate: "92%" },
    { name: "Capitol Site", reports: 22, resolvedRate: "86%" },
    { name: "Banilad", reports: 19, resolvedRate: "95%" },
    { name: "Parian", reports: 17, resolvedRate: "76%" },
    { name: "Ermita", reports: 15, resolvedRate: "80%" },
  ],
};
